# SPDX-License-Identifier: Apache-2.0
#
# Copyright (C) 2017, ARM Limited and contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

sudo: required
language: python
install:
  - pip install --upgrade trappy bart-py devlib psutil wrapt matplotlib
    future jupyter sphinx ruamel.yaml
script:
  - cd $TRAVIS_BUILD_DIR
  - 'echo backend : Agg > matplotlibrc' # Otherwise it tries to use tkinter
  - export PATH=$TRAVIS_BUILD_DIR/tools/x86_64/:$PATH # For trace-cmd
  - source init_env && lisa-test tests/lisa/
  # -W is like -Werror.
  # Ideally we should use -n too, which is like -Wall, but we have too many errors for that.
  - cd doc/ && sphinx-build -W -b html . _build/html
